"""initial migration

Revision ID: 36d2a02e240f
Revises: 
Create Date: 2020-06-27 19:36:34.819949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36d2a02e240f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    op.drop_table('procesamientos')
    op.drop_table('opinion')
    op.drop_table('evaluador')
    op.alter_column('usuario', 'nombre_usuario',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('usuario', 'password_usuario',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'password_usuario',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('usuario', 'nombre_usuario',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_table('evaluador',
    sa.Column('idevaluador', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('idopinion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clasifiopi', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('clasifiopi1', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('idevaluacion', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['idevaluador'], ['usuario.id_usuario'], name='evaluador_idevaluador_fkey'),
    sa.ForeignKeyConstraint(['idopinion'], ['opinion.idopinion'], name='eva_opi'),
    sa.PrimaryKeyConstraint('idevaluacion', name='evaluador_pkey')
    )
    op.create_table('opinion',
    sa.Column('timestamp', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('student', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('opinion', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idopinion', sa.INTEGER(), server_default=sa.text("nextval('opinion_idopinion_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('edad', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('semester', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('nombres', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('timestamp', 'student', name='pk_opid'),
    sa.UniqueConstraint('idopinion', name='id'),
    postgresql_ignore_search_path=False
    )
    op.create_table('procesamientos',
    sa.Column('id_procesamiento', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('plagio', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('largo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('idopinion', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['idopinion'], ['opinion.idopinion'], name='procesamientos_idopinion_fkey'),
    sa.PrimaryKeyConstraint('id_procesamiento', name='procesamientos_pkey')
    )
    op.create_table('students',
    sa.Column('semestre', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('programa', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tdocumento', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('numero', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('codigo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('codigoinscrip', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('nombreestudiante', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('genero', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('colegio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tipocolegio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cuidadcolegio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('especialidad', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('estadocivil', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tarjetamilitar', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('paisnacimiento', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('deptonacimiento', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ciudadnacimiento', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fechanacimiento', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('paisrecidencia', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('deptorecidencia', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ciudadresidencia', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('numhijos', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tipovovienda', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('numpersonasacargo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('estrato', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sisben', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('deusacasa', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('actividadeconomica', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rangosalarial', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('financiamatricula', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('grupodiscapacidad', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('discapacidad', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resguardoindigena', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('grupoetnico', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('victima', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('desplazado', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('students', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('temporal', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('idstudent', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('nombreestudiante', name='students_pkey')
    )
    # ### end Alembic commands ###
